#The first line is used for comment
!counter 0x76 計數器（大逆轉BOX）
!counter 0x77 冠計數器
!counter 0x78 萬倍計數器
!setname 0x2e2 白夜騎士
!setname 0x2e3 戴達羅斯
!setname 0x2e4 艮鬼
!setname 0x2e5 具象天使
!setname 0x2e6 奧藝
!setname 0x2e7 迪亞克托羅斯
!setname 0x2e8 梅迪烏斯
!setname 0x2e9 假面魔蹈士
!setname 0x2ea 塞尼特
